apiVersion: v1
kind: Service
metadata:
  name: backstage-connect
  labels:
    # Enables "zarf connect wordpress-blog"
    zarf.dev/connect-name: backstage
  annotations:
    zarf.dev/connect-description: "The Backstage HTTP backend"
spec:
  selector:
    app.kubernetes.io/instance: backstage
    app.kubernetes.io/name: backstage
  ports:
    - name: http
      port: 7007
      protocol: TCP
      targetPort: 7007
